### PR TITLE
Simplify cvar declaration to a single line of each

### PR DESCRIPTION
**Pull request by LegendaryGuard**
It's an improvement in development efficiency by simplifying the declaration of cvars. 
Previously, it was necessary to write 3 lines of code and modify 2 different files to declare a cvar. 

With this modification, the declaration can be done in a single line of code in a single file, significantly reducing the time and effort required. 
This not only simplifies the development process but also enhances code readability by reducing redundancy. 
This improvement will contribute to faster and more efficient development in the project.

Credits: Razor

### CODE REVIEW

**Review by ec- — APPROVED** [review]

**Comment by WofWca** [comment]
Great work, @LegendaryGuard this really saves a lot of time and brainpower!

Would you please also license this patch under GPLv2-or-later so that it can be applied to other mods?

Edit: oh I just saw the "Credits" line. How can that person be contacted?
Edit 2: @Razish are you the author?

**Comment by LegendaryGuard** [comment]
> Great work, @LegendaryGuard this really saves a lot of time and brainpower!
> 
> Would you please also license this patch under GPLv2-or-later so that it can be applied to other mods?
> 
> Edit: oh I just saw the "Credits" line. How can that person be contacted?

@WofWca 
That copyright header for the new code files? Like this?
```c
// Copyright (C) 1999-2000 Id Software, Inc.
//
// g_cvar.h -- header to declare g_* cvars
```

Or like this? (reference: https://github.com/ec-/baseq3a/blob/master/code/game/g_unlagged.c#L1)
```c
//
// Based on Razor's code.
//
```
That's what I see in this repository. Perhaps you're referring to Quake 3 Arena GPLv2 header?
I hadn't thought about it before. But I think the credit should go to whoever actually did it.

> Edit 2: @Razish are you the author?

Yes, @Razish is the one who started this.

**Comment by WofWca** [comment]
Yes, a "Copyright" would be ideal, but I was asking for just a "verbal" permission here on GitHub. Then I will make the commit and PRs myself.
This repo is not licensed under GPLv2-or-later, unlike let's say ioquake3, so I cannot legally port this change to other GPLv2-based mods.

**Comment by LegendaryGuard** [comment]
OMG! You're right, the repo doesn't have anything related to GPL license.  😰
I wonder if anyone is free to use the code in their mods. 

I just checked that cvar macro code files come from a GPLv2 game, reference: https://github.com/JACoders/OpenJK/blob/master/codemp/game/g_xcvar.h
although the way to define is different.

**Comment by WofWca** [comment]
> macro code files come from a GPLv2 game

Ah, that's better, thank you! But GPL-2.0-or-later would be even better, otherwise a GPL-2.0-or-later mod would have to "downgrade" to GPL-2.0-only in order to incorporate the change.

> I wonder if anyone is free to use the code in their mods.

Yes, this part also seems ambiguous to me. The QIIIA SDK license (which this project uses) doesn't say much about these freedoms.

**Comment by LegendaryGuard** [comment]
Just checked some stuff, most of the code contributed in this repo here looks original made by users like us.

It's pretty weird that a licensed SDK code would be open in this part, QIIIA has already opensourced this code from a couple of decades ago.

Authors and contributors like us and others also distribute it under GPLv2 (unless if that applies in this perspective) in their side project.

Having a license that looks a bit outdated doesn't make sense. Because most of contributors here are doing it in the opensourced way without realizing that old license was here.

**Comment by WofWca** [comment]
We had a bit of a discussion about this in #59.

I'm not sure if it's fair to call the license "outdated" though. This project also contains original models and icons (in higher quality), and those were never released under GPL (which I attempted to address in #59), so the license can't be simply "updated", unfortunately.
Although what would make sense IMO is defaulting further patches to be dual-licensed, so that people don't have to ask for explicit permission as I did 2 hours ago.

**Comment by LegendaryGuard** [comment]
I think here clarifies a bit:

> [Q3A SDK is way more permissive: you can develop a competitive mod with closed-source anti-cheat for example, and you can still contribute to open-source development, at good will, and most q3a devs are](https://github.com/ec-/baseq3a/pull/59#issuecomment-3568010304)

I think, unless the author, who has the SDK licensed mod, can relicense to another license under its will or not, if the users ask permission to use it in their code. Also depends if the author said that you can use it, in some cases, that's allowed.

IIRC, I remember a case of migrating a Doom3 mod project to dhewm3 mods (GPLv3 license), this mod was called HeXen: Edge Of Chaos, we talked with the author because it was D3 SDK licensed.
The author gave us the permission to relicense the mod with its GPL-lower-or-higher license, and dhewm3 maintainer pushed the changes to save this mod directly with the relicensed license.

I don't know how this goes here, but if the contributors here did it in the freedom way, that's another thing. It shouldn't impede their freedom to use in their GPL licensed mods.
If someone didn't it with this 'freedom' way and doesn't allow to relicense, then maybe we should abstain to use the code legally.

**Pull request merged**
