### PR TITLE
Don't use uninitialized ps from BotAI_GetClientState.

### PR DESCRIPTION
**Pull request by KuehnhammerTobias**
I'll start a series of pull requests with bugfixes from ioquake3, not implemented in baseq3 until now.

CHANGES: Don't use uninitialized ps from BotAI_GetClientState.
NOTES: https://github.com/ioquake/ioq3/commit/6e340f9a5b185b58b80063655cd4cffd463b707c

### CODE REVIEW

**Comment by ec-** [comment]
It is not possible to do direct copy of GPLv2 code here

**Comment by KuehnhammerTobias** [comment]
Ah ok, sorry, I thought both are GPL v2.

**Comment by ec-** [comment]
You might merge your *clean room* code here, intention of this repo is to provide most recent codebase at Q3A SDK license so it can be used to create competition mods (where you might not want to publish *all* sources to avoid in-game cheating)

**Comment by KuehnhammerTobias** [comment]
Excuse me to ask this here, but will you fix the bugs within this repository on your own than? For example the 'spectators-flying-through-doors' bug that was fixed 10 (!) years ago?
I mean it's okay to me, cuz I still use my own mod code, I just think maybe some more people don't know what baseq3e should be made for, if it shouldn't/wouldn't be the de-facto game mod for Q3e .... maybe I'm completely wrong.

**Comment by em92** [comment]
> intention of this repo is to provide most recent codebase at Q3A SDK license

Could you also upload this license to repo, please? I also though, that baseq3a is under GPLv2

**Pull request closed without merging**
